[Platform]
name = "CTE-AMD"
cpu = "AMD EPYC 7742"
cpu-freq = 2.90
motherboard = "Intel xxx"
cache-line = 64
mem = "brandname model 8GB"
mem-type = "DDR4"
mem-freq = 3200
mem-max-channels = 8
stlb-hit-latency = 2.06591

[Experiments]
stream-core-list = "1-63"
stream-core-count = 63
stream-core-count-socket = 63 
stream-numactl-additional-args = ""
ptrchase-core = "0"
ptrchase-numactl-additional-args = ""

rwratio-min = 0
rwratio-max = 100
rwratio-step = 2

stream-pauses = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80, 90, 100, 120, 140, 160, 180, 200, 220, 260, 300, 340, 380, 450, 550, 600, 700, 800, 900, 1000, 1500, 2000, 3000, 5000, 40000, 100000, 500000, 1000000]


point-reps = 1
bw-meas-reps = 1
lat-meas-reps = 1

time-stream-stabilize= 20
time-after-bw = 4
time-after-stream-termination = 0

[Counters]
bw-tool = "perf"
bw-tool-path = "perf"
bw-tool-cores = "0"
bw-tool-sample-time = "5s"
bw-tool-counters="""\
"""
lat-tool = "perf"
lat-tool-path = ""
lat-tool-counters = ""

[Processing]
smooth-savgol-window-length = 11
smooth-savgol-polyorder = 3


[Benchmarks]
ptrchase-num-instructions = 300000000
ptrchase-num-iterations = 5000
ptrchase-array-size = "256 * 1024 * 1024" 
