[Platform]
name = "hostname"
cpu = "Intel Xeon Platinum 8260L (Cascade Lake)"
cpu-freq = 2.4
motherboard = "Intel S2600WFD"
mem = "Intel Optane NMA1XXD128GPS 128GB"
mem-type = "Optane"
mem-freq = 2666
mem-max-channels = 6
stlb-hit-latency = 9

[Experiments]
stream-core-list = "1-23,25-47"
stream-core-count = 46
stream-core-count-socket = 23 
stream-numactl-additional-args = "--membind 2,3"
ptrchase-core = "0"
ptrchase-numactl-additional-args = "--membind 2"

rwratio-min = 50
rwratio-max = 100
rwratio-step = 2

stream-pauses = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80, 90, 100, 120, 140, 160, 180, 200, 220, 260, 300, 340, 380, 450, 550, 600, 700, 800, 900, 1000, 1500, 2000, 3000, 5000, 40000, 100000]

point-reps = 1
bw-meas-reps = 3
lat-meas-reps = 3

time-stream-stabilize= 10
time-after-bw = 2
time-after-stream-termination = 2

[Counters]
bw-tool = "likwid"
bw-tool-path = "likwid-perfctr"
bw-tool-cores = "0-23"
bw-tool-sample-time = "5s"
bw-tool-counters="""\
INSTR_RETIRED_ANY:FIXC0,\
CPU_CLK_UNHALTED_CORE:FIXC1,\
CPU_CLK_UNHALTED_REF:FIXC2,\
LONGEST_LAT_CACHE_MISS:PMC0,\
PMM_RPQ_INSERTS:MBOX0C0,\
PMM_WPQ_INSERTS:MBOX0C1,\
PMM_RPQ_INSERTS:MBOX1C0,\
PMM_WPQ_INSERTS:MBOX1C1,\
PMM_RPQ_INSERTS:MBOX2C0,\
PMM_WPQ_INSERTS:MBOX2C1,\
PMM_RPQ_INSERTS:MBOX3C0,\
PMM_WPQ_INSERTS:MBOX3C1,\
PMM_RPQ_INSERTS:MBOX4C0,\
PMM_WPQ_INSERTS:MBOX4C1,\
PMM_RPQ_INSERTS:MBOX5C0,\
PMM_WPQ_INSERTS:MBOX5C1\
"""
lat-tool = "perf"
lat-tool-path = "perf"
lat-tool-counters = "cycles:u,instructions:u,r2008:u,r1008:u"

[Processing]
smooth-savgol-window-length = 11
smooth-savgol-polyorder = 3


[Benchmarks]
ptrchase-num-instructions = 20000000
ptrchase-num-iterations = 5000
ptrchase-array-size = "1 * 1024 * 1024 * 1024" 
