[Platform]
name = "HiFive"
cpu = "Quad-core 64-bit SiFive U74"
cpu-freq = 1.2
motherboard = "Intel xxx"
l1-cache-size=65536
l2-cache-size=524288
l3-cache-size=33554432
cache-line = 64
mem-size = 274877906944
mem = "brandname model 4GB"
mem-type = "DDR4"
mem-freq = 1866
mem-max-channels = 1
stlb-hit-latency = 7


[Experiments]
stream-core-list = "1-3"
stream-core-count = 3
stream-core-count-socket = 3 
stream-numactl-additional-args = ""
ptrchase-core = "0"
ptrchase-numactl-additional-args = ""

rwratio-min = 68
rwratio-max = 100
rwratio-step = 2

stream-pauses = [0, 10, 20, 30, 40, 50, 60, 70, 80, 100, 120, 140, 180, 220, 260,  340, 380, 450, 550, 700, 800,  1000, 1500, 2000, 5000, 40000, 500000, 1000000]


point-reps = 1
bw-meas-reps = 1
lat-meas-reps = 1

time-stream-stabilize= 20
time-after-bw = 3
time-after-stream-termination = 2

[Counters]
bw-tool = "perf"
bw-tool-path = "perf"
bw-tool-cores = "0"
bw-tool-sample-time = "10s"
bw-tool-counters="""\
"""
lat-tool = "perf"
lat-tool-path = ""
lat-tool-counters = ""

[Processing]
smooth-savgol-window-length = 11
smooth-savgol-polyorder = 3


[Benchmarks]
ptrchase-num-instructions = 200000000
ptrchase-num-iterations = 50000
ptrchase-array-size = "128*1024*1024" 
