##########################################################
# This section describes the platform used for measuring #
##########################################################
[Platform]

# Name of the platform (used in reporting).
name = "MareNostrum 3"

# Processor model (used in reporting).
cpu = "SandyBridge"

# CPU frequency in GHz (used in latency calculation).
cpu-freq = 3

# Motherboard model (used in reporting).
motherboard = "NaN"

# Memory model (used in reporting).
mem = "SAMSUNG model 8GB"

# Memory technology (used in reporting).
mem-type = "DDR3"

# Memory frequency (used in reporting and post-processing).
mem-freq = 1600

# Maximum number of memory channels on the motherboard
mem-max-channels = 8

# Hit latency of the secondary level TLB (used to calculate penalty of virtual-to-physical address translation).
stlb-hit-latency = 7


#########################################
# This section configures the measuring #
#########################################
[Experiments]

# Processor cores used to run stream benchmark (passed to numactl).
stream-core-list = "1-7"

# Number of cores used to run stream benchmark (passed to mpirun). Has to match the number of cores specified in the parameter above.
stream-core-count = 7

# Number of cores used to run stream benchmark on each socket. Has to match the total number of cores specified in the parameter above divided by 2total .
# TODO explain on the README why we leave core zero of the second socket out of the measurements
stream-core-count-socket = 14

# Additional parameters passed to numactl when launching stream
stream-numactl-additional-args = ""

# Processor core used to run pointer-chasing benchmark.
ptrchase-core = "0"

# Additional parameters passed to numactl when launching pointer-chasing bechmark
ptrchase-numactl-additional-args = ""

# Range and step controlling the read:write ratio of memory traffic (interval limits are inclusive).
rwratio-min = 50
rwratio-max = 100
rwratio-step = 2

# List of pauses used to run stream. Pauses control the intensity of memory traffic.
stream-pauses = [0, 100, 1000]

# How many separate stream runs are done for each point (rw_ratio, pause).
point-reps = 1

# How many times bandwidth is measured.
bw-meas-reps = 1

# How many times latency is measured.
lat-meas-reps = 1

# Time in seconds spent in sleep after launching stream benchmark. This allows for bandwidth to stabilize.
time-stream-stabilize= 10

# Time in seconds spent in sleep after measuring bandwidth
time-after-bw = 1

# Time in seconds spent in sleep after terminating sleep benchmark. This allows for system to come to the stable state before launching next stream instance.
time-after-stream-termination = 1


#########################################################################
# This section configures the tool used to measure performance counters #
#########################################################################
[Counters]

# Name of the tool used to measure bandwidth (used for internally by StressMe).
bw-tool = "likwid"

# Command or full path to the tool used to measure bandwidth.
bw-tool-path = "likwid-perfctr"

# List of cores whose performance counters are considered for bandwidth measurement (passed to the bandwidth measuring tool).
bw-tool-cores = "0-3"

# Measuring time for one bandwidth measurement (in the format expected by the bandwidth-measuring tool).
bw-tool-sample-time = "5s"

# List of counters to sample for bandwidth measurement (in the format expected by the bandwidth-mesuring tool).
bw-tool-counters="""\
INSTR_RETIRED_ANY:FIXC0,\
CPU_CLK_UNHALTED_CORE:FIXC1,\
CPU_CLK_UNHALTED_REF:FIXC2,\
LONGEST_LAT_CACHE_MISS:PMC0,\
DRAM_READS:MBOX0C1,\
DRAM_WRITES:MBOX0C2\
"""

# Name of the tool used to measure memory access latency (used internally by StressMe).
lat-tool = "perf"

# Command or full path to the tool used to measure latency.
lat-tool-path = "perf"

# List of counters to sample for latency measurement (in the format expected by the latency-measuring tool).
lat-tool-counters = "cycles:u,instructions:u,r2008:u,r1008:u"

#######################################################
# This section configures the post-processing scripts #
#######################################################
[Processing]

# Parameter of the savgol_filter function used to smooth the bandwidth-latency curves. See python docs for further details.
smooth-savgol-window-length = 11

# Parameter of the savgol_filter function used to smooth the bandwidth-latency curves. See python docs for further details.
smooth-savgol-polyorder = 3


############################################################
# This section configures the benchmark compiling settings #
############################################################
[Benchmarks]

# ptrchase number of instructions to be executed
# TODO: check README for more information on how to configure this parameter
ptrchase-num-instructions = 20000000

# ptrchase number of iterations
# TODO: check README for more information on how to configure this parameter
ptrchase-num-iterations = 5000

# ptrchase array size
# TODO: check README for more information on how to configure this parameter
ptrchase-array-size = "1 * 1024 * 1024 * 1024" 

