[Platform]
name = "hostname"
cpu = "Intel Xeon Gold 5218 (Cascade Lake)"
cpu-freq = 2.3
motherboard = "GIGABYTE MR91-FS0-00"
mem = "Samsung M393A2K40CB2-CTD 16GB"
mem-type = "DDR4"
mem-freq = 2666
mem-max-channels = 6
stlb-hit-latency = 9

[Experiments]
stream-core-list = "1-15,17-31"
stream-core-count = 30
stream-core-count-socket = 15
stream-numactl-additional-args = ""
ptrchase-core = "0"
ptrchase-numactl-additional-args = ""

rwratio-min = 50
rwratio-max = 100
rwratio-step = 2

stream-pauses = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80, 90, 100, 120, 140, 160, 180, 200, 220, 260, 300, 340, 380, 450, 550, 600, 700, 800, 900, 1000, 1500, 2000, 3000, 5000, 40000, 100000]

point-reps = 1
bw-meas-reps = 3
lat-meas-reps = 3

time-stream-stabilize= 10
time-after-bw = 2
time-after-stream-termination = 2

[Counters]
bw-tool = "likwid"
bw-tool-path = "likwid-perfctr"
bw-tool-cores = "0-15"
bw-tool-sample-time = "5s"
bw-tool-counters="""\
INSTR_RETIRED_ANY:FIXC0,\
CPU_CLK_UNHALTED_CORE:FIXC1,\
CPU_CLK_UNHALTED_REF:FIXC2,\
LONGEST_LAT_CACHE_MISS:PMC0,\
CAS_COUNT_RD:MBOX0C0,\
CAS_COUNT_WR:MBOX0C1,\
CAS_COUNT_RD:MBOX1C0,\
CAS_COUNT_WR:MBOX1C1,\
CAS_COUNT_RD:MBOX2C0,\
CAS_COUNT_WR:MBOX2C1,\
CAS_COUNT_RD:MBOX3C0,\
CAS_COUNT_WR:MBOX3C1,\
CAS_COUNT_RD:MBOX4C0,\
CAS_COUNT_WR:MBOX4C1,\
CAS_COUNT_RD:MBOX5C0,\
CAS_COUNT_WR:MBOX5C1\
"""
lat-tool = "perf"
lat-tool-path = "perf"
lat-tool-counters = "cycles:u,instructions:u,r2008:u,r1008:u"

[Processing]
smooth-savgol-window-length = 11
smooth-savgol-polyorder = 3

[Benchmarks]
ptrchase-num-instructions = 20000000
ptrchase-num-iterations = 5000
ptrchase-array-size = "1 * 1024 * 1024 * 1024"
